---
title: 'Disenchantment Bay Tagging: Data Review'
author: "Stacie Hardy"
date: "4/18/2022"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(stringr)
library(lubridate)
library(RPostgreSQL)
library(ggplot2)
library(reshape2)
library(scales)

# Connect to DB and get starting data
con <- RPostgreSQL::dbConnect(PostgreSQL(), 
                              dbname = Sys.getenv("pep_db"), 
                              host = Sys.getenv("pep_ip"), 
                              port = Sys.getenv("pep_port"),
                              user = Sys.getenv("pep_user"), 
                              password = "$e@l")

haulout <- RPostgreSQL::dbGetQuery(con, "SELECT * FROM telem.tbl_wc_haulout WHERE deployid LIKE \'PV2016%\'") 

haulout <- haulout %>%
  select(deployid, haulout_start_dt, haulout_end_dt) %>%
  filter(!is.na(haulout_end_dt)) %>%
  mutate(haulout_start_dt = as.POSIXct(haulout_start_dt, origin = as.Date("1970-01-01"), tz = "GMT")) %>%
  mutate(haulout_end_dt = as.POSIXct(haulout_end_dt, origin = as.Date("1970-01-01"), tz = "GMT"))

haulout_m <- melt(haulout, id.vars = "deployid") %>%
  mutate(value = as.POSIXct(value, origin = as.Date("1970-01-01"), tz = "GMT")) %>%
  arrange(deployid, value) 
haulout_m$eventID <- rep(seq(1, nrow(haulout_m)/2, 1), each=2)

# NEED TO ADD ROWS WHERE START/END TIMES COVER DAY CHANGE...do this by creating rows for all hours between start and end of a deployment

deployids <- unique(haulout$deployid)
```

```{r figures, results = 'all'}
# Figure 1
lims <- c(as.POSIXct("2021-01-01 00:00:00", origin = as.Date("1970-01-01"), tz = "GMT"), as.POSIXct("2021-01-02 00:00:00", origin = as.Date("1970-01-01"), tz = "GMT"))

for (i in 1:length(deployids)) {
  haulout_m2 <- haulout_m %>%
    filter(deployid == deployids[i]) %>%
    mutate(time = as.POSIXct(paste('2021-01-01', strftime(value, format = "%H:%M:%S")), tz = "GMT"),
         date = as_date(value)) %>%
    mutate(end_time = lead(time, 1)) %>%
    mutate(time = as.POSIXct(ifelse(end_time < time & variable == "haulout_start_dt", time - 3600 * 24, time), origin = as.Date("1970-01-01"), tz = "GMT"))

p <- ggplot(haulout_m2) +
  geom_line(aes(time, date, group = eventID, color = deployid), size = 1.5) +
  #coord_polar(start = 0, direction = 1) +
  scale_x_datetime(limits = lims, breaks = date_breaks("2 hour"), date_labels = "%H:%M:%S") +
  ylim(min(haulout_m2$date) - 1, max(haulout_m2$date)) +
  xlab('Time of Day') +
  ylab('Date') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

print(p)
}

```